yii-world/models/Continent.php
<?php


namespace app\models;


use yii\db\ActiveRecord;

class Continent extends ActiveRecord
{

}

yii-world/controllers/ContinentController.php
<?php


namespace app\controllers;


use app\models\Country;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\Continent;

class ContinentController extends Controller
{
    public function actionIndex()
    {
        $continents = Continent::find()->asArray()->all();
        return $this->render('index', ['continents' => $continents]);
    }

    public function actionView($code = "AF")
    {
        $continent = Continent::find()->where(['code'=>$code])->one();

        $countriesDataProvider = new ActiveDataProvider([
           'query' => Country::find()->where(['continent_id'=>$continent->continent_id]),
           'pagination'=>[
               'pageSize' => 20,
           ]
        ]);

        return $this->render('view', compact('continent', 'countriesDataProvider'));
    }
}

yii-world/controllers/CountryController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Country;
use app\models\CountrySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CountryController implements the CRUD actions for Country model.
 */
class CountryController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Country models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CountrySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Country model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Country model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Country();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->country_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Country model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->country_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Country model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Country model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Country the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Country::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

yii-world/views/continent/_country.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
?>
<a href="<?= Url::to(['country/view', 'id'=>$model['country_id']]); ?>" class="list-group-item list-group-item-action">
    <?= Html::img('@web/images/countries/png100px/'.strtolower($model['code']).'.png', ['alt'=>$model['name']]) ?>
    <?= Html::encode($model->name); ?>
</a>

yii-world/views/continent/index.php
<?php
    use yii\helpers\Html;
    use yii\helpers\Url;
?>

<?php
$this->params['breadcrumbs'][] = ['label' => 'Continents', 'url' =>['continent/index']];
?>

<div class="container">
    <div class="row">
    <?php foreach ($continents as $continentItem): ?>
    <div class="col-md-4">
        <div class="panel panel-default" style="min-height: 500px">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <a href="<?= Url::to(['continent/view', 'code' => $continentItem['code']]); ?>" class="list-group-item">
                    <?=Html::encode($continentItem['name']) ?>
                    </a>
                    <?=Html::img('@web/images/continents/'. strtolower($continentItem['code']). '.png', ['alt' => 'My logo', 'width'=>'100%']) ?>
                </h3>
            </div>
            <div class="panel-body">
                <?=Html::encode($continentItem['description']) ?>
            </div>
        </div>
    </div>
    <? endforeach; ?>
</div>
</div>

yii-world/views/continent/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\ListView;

$this->title = $continent->name;
$this->params['breadcrumbs'][] = ['label' => 'Continents', 'url' =>['continent/index']];
$this->params['breadcrumbs'][] = ['label' => $continent->name, 'url' =>['continent/view', 'code'=>$continent->code]];
?>

<section id="continent-view">
    <div class="container">
        <h1><?= Html::encode($this->title) ?></h1>
        <p><?= Html::encode($continent->description) ?></p>
    </div>
</section>

<?= ListView::widget([
   'dataProvider' => $countriesDataProvider,
   'itemView' => '_country',
    'layout' => "{items}\n{summary}\n{pager}",
    'options' => [
            'class' => 'list-group'
    ],
    'itemOptions' => [
            'tag' => false,
    ]
]); ?>