yii-world/models/Country.php
<?php


namespace app\models;



use yii\db\ActiveRecord;

class Country extends ActiveRecord
{
    public function getContinent()
    {
        return $this->hasOne(Continent::className(), ['continent_id'=>'continent_id']);
    }
}

yii-world/controllers/ContinentController.php
<?php


namespace app\controllers;


use app\models\Country;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\Continent;

class ContinentController extends Controller
{
    public function actionIndex()
    {
        $continents = Continent::find()->asArray()->all();
        return $this->render('index', ['continents' => $continents]);
    }

    public function actionView($code = "AF")
    {
        $continent = Continent::find()->where(['code'=>$code])->one();

        $countriesDataProvider = new ActiveDataProvider([
           'query' => Country::find()->where(['continent_id'=>$continent->continent_id]),
           'pagination'=>[
               'pageSize' => 20,
           ]
        ]);

        return $this->render('view', compact('continent', 'countriesDataProvider'));
    }
}

yii-world/controllers/CountryController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Country;
use app\models\CountrySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CountryController implements the CRUD actions for Country model.
 */
class CountryController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Country models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CountrySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Country model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Country model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Country();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->country_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Country model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->country_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Country model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Country model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Country the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Country::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

yii-world/views/country/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Continent;

/* @var $this yii\web\View */
/* @var $model app\models\Country */
/* @var $form yii\widgets\ActiveForm */
?>

<?php
$i = 1;
foreach ($continent as $item)
{
    $items[$i] = $item['name'];
    $i++;
}
$params = [
        'prompt'=>'Select continent'
];
?>

<div class="country-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'country_id')->textInput() ?>

    <?= $form->field($model, 'code')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'official_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'iso3')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'number')->textInput() ?>

    <?= $form->field($model, 'currency')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'capital')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'area')->textInput() ?>

    <?= $form->field($model, 'continent_id')->dropDownList($items, $params) ?>

    <?= $form->field($model, 'coords')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'display_order')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

yii-world/views/country/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\CountrySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="country-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'country_id') ?>

    <?= $form->field($model, 'code') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'official_name') ?>

    <?= $form->field($model, 'iso3') ?>

    <?php // echo $form->field($model, 'number') ?>

    <?php // echo $form->field($model, 'currency') ?>

    <?php // echo $form->field($model, 'capital') ?>

    <?php // echo $form->field($model, 'area') ?>

    <?php // echo $form->field($model, 'continent_id') ?>

    <?php // echo $form->field($model, 'coords') ?>

    <?php // echo $form->field($model, 'display_order') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

yii-world/views/country/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Country */

$this->title = 'Create Country';
$this->params['breadcrumbs'][] = ['label' => 'Countries', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="country-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

yii-world/views/country/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\CountrySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Countries';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="country-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Country', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'country_id',
            'code',
            'name',
            'official_name',
            'iso3',
            //'number',
            //'currency',
            //'capital',
            //'area',
            //'continent_id',
            //'coords',
            //'display_order',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

yii-world/views/country/update.php
<?php

use yii\helpers\Html;
use app\models\Continent;


/* @var $this yii\web\View */
/* @var $model app\models\Country */

$this->title = 'Update Country: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Countries', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->country_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="country-update">

    <h1><?= Html::encode($this->title) ?></h1>
    <? $continent = Continent::find()->all(); ?>
    <?= $this->render('_form', [
        'model' => $model, 'continent' => $continent
    ]) ?>

</div>

yii-world/views/country/view.php
<?php

use yii\widgets\DetailView;
use yii\helpers\Url;
?>

<?php
$this->params['breadcrumbs'][] = ['label' => 'Continents', 'url' =>['continent/index']];
$this->params['breadcrumbs'][] = ['label' => $model->continent->name, 'url' =>['continent/view', 'code'=>$model->continent->code]];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' =>['country/view', 'id'=>$model->country_id]];
?>
<a class="btn btn-primary" href="<?=Url::to(['country/update', 'id'=>$model->country_id]); ?>" role="button">Update</a>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6">
            <?php
            echo DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'official_name',
                    'currency',
                    'area',
                    'capital',
                    [
                        'attribute'=>'flag',
                        'value'=>'@web/images/countries/png250px/' . strtoLower($model->code) . '.png',
                        'format' => ['image']
                    ]
                ],
            ]);
            ?>
        </div>
        <div class="col-12 col-md-6">
            <script
                    src="https://maps.googleapis.com/maps/api/js?&callback=initMap&libraries=&v=weekly&sensor=false"
                    defer
            ></script>
            <style type="text/css">
                /* Set the size of the div element that contains the map */
                #map {
                    height: 400px;
                    /* The height is 400 pixels */
                    width: 100%;
                    /* The width is the width of the web page */
                }
            </style>
            <script>
                // Initialize and add the map
                function initMap() {
                    // The location of Uluru
                    const uluru = { lat: -25.344, lng: 131.036 };
                    // The map, centered at Uluru
                    const map = new google.maps.Map(document.getElementById("map"), {
                        zoom: 4,
                        center: uluru,
                    });
                    // The marker, positioned at Uluru
                    const marker = new google.maps.Marker({
                        position: uluru,
                        map: map,
                    });
                }
            </script>
            <div id="map"></div>
        </div>
    </div>
</div>